import 'dotenv/config';
import { db } from './db';
import { books } from './schema';

const bookData = [
  // ─── MINDSET — READ (status: 'read') ───
  { title: 'As a Man Thinketh', author: 'James Allen', category: 'mindset', status: 'read' },
  { title: 'Outliers', author: 'Malcolm Gladwell', category: 'mindset', status: 'read' },
  { title: 'Blink', author: 'Malcolm Gladwell', category: 'mindset', status: 'read' },
  { title: 'Talking to Strangers', author: 'Malcolm Gladwell', category: 'mindset', status: 'read' },
  { title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson', category: 'mindset', status: 'read' },
  { title: 'Atomic Habits', author: 'James Clear', category: 'mindset', status: 'read' },
  { title: 'The Alchemist', author: 'Paulo Coelho', category: 'mindset', status: 'read' },
  { title: 'IKIGAI', author: null, category: 'mindset', status: 'read' },
  { title: 'The 10X Rule', author: 'Grant Cardone', category: 'mindset', status: 'read' },
  { title: 'The Power of Discipline', author: null, category: 'mindset', status: 'read' },
  { title: '48 Laws of Power', author: 'Robert Greene', category: 'mindset', status: 'read' },
  { title: 'The Art of Seduction', author: 'Robert Greene', category: 'mindset', status: 'read' },
  { title: 'The Rules of Wealth', author: 'Richard Templar', category: 'mindset', status: 'reading' },
  { title: 'The Rules of Thinking', author: 'Richard Templar', category: 'mindset', status: 'reading' },
  { title: 'Rework', author: 'Jason Fried', category: 'mindset', status: 'read' },
  { title: 'The Power of Habits', author: 'Charles Duhigg', category: 'mindset', status: 'read' },
  { title: 'The Art of Laziness', author: 'Library Mindset', category: 'mindset', status: 'read' },
  { title: 'The Compound Effect', author: 'Darren Hardy', category: 'mindset', status: 'read' },
  { title: 'Trading in the Zone', author: 'Mark Douglas', category: 'mindset', status: 'read' },
  { title: 'The Real Value of Wealth', author: null, category: 'mindset', status: 'read' },
  { title: 'The Psychology of Money', author: 'Morgan Housel', category: 'mindset', status: 'read' },
  { title: 'Same as Ever', author: 'Morgan Housel', category: 'mindset', status: 'read' },
  { title: 'Psychology Triggers', author: 'Peter Hollins', category: 'mindset', status: 'read' },
  { title: 'The Leader Who Had No Title', author: null, category: 'mindset', status: 'read' },
  { title: 'The Obstacle is the Way', author: 'Ryan Holiday', category: 'mindset', status: 'read' },
  { title: 'Stillness is the Key', author: 'Ryan Holiday', category: 'mindset', status: 'read' },
  { title: 'Ego is the Enemy', author: 'Ryan Holiday', category: 'mindset', status: 'read' },
  { title: 'The Daily Stoic', author: 'Ryan Holiday', category: 'mindset', status: 'read' },
  { title: 'The Daily Laws', author: 'Robert Greene', category: 'mindset', status: 'read' },
  { title: 'The Almanack of Naval Ravikant', author: null, category: 'mindset', status: 'read' },
  { title: 'The Unfair Advantage', author: null, category: 'mindset', status: 'read' },
  { title: 'The Power of Now', author: 'Eckhart Tolle', category: 'mindset', status: 'read' },
  { title: 'Thinking Fast and Slow', author: 'Daniel Kahneman', category: 'mindset', status: 'read' },
  { title: 'Zero to One', author: 'Peter Thiel', category: 'mindset', status: 'read' },
  { title: 'Think and Grow Rich', author: 'Napoleon Hill', category: 'mindset', status: 'read' },
  { title: 'The Richest Man in Babylon', author: 'George Clason', category: 'mindset', status: 'read' },
  { title: 'How to Win Friends and Influence People', author: 'Dale Carnegie', category: 'mindset', status: 'read' },
  { title: 'How to Stop Worrying and Start Living', author: 'Dale Carnegie', category: 'mindset', status: 'read' },
  { title: 'Million Success Habit', author: 'Dean Graziosi', category: 'mindset', status: 'read' },
  { title: 'The 7 Habits of Highly Effective People', author: 'Stephen Covey', category: 'mindset', status: 'read' },
  { title: 'Becoming', author: 'Michelle Obama', category: 'mindset', status: 'read' },
  { title: 'Homo Deus', author: 'Yuval Noah Harari', category: 'mindset', status: 'read' },
  { title: 'Sapiens', author: 'Yuval Noah Harari', category: 'mindset', status: 'read' },
  { title: '21 Lessons of the 21st Century', author: 'Yuval Noah Harari', category: 'mindset', status: 'read' },
  { title: 'A Technique for Producing Ideas', author: 'James Wood Young', category: 'mindset', status: 'read' },
  { title: 'Steal Like an Artist', author: 'Austin Kleon', category: 'mindset', status: 'read' },
  { title: 'Finish Everything You Start', author: 'Jan Yager', category: 'mindset', status: 'read' },
  { title: 'The Parable of Dollar', author: null, category: 'mindset', status: 'read' },

  // ─── MINDSET — TO READ (status: 'to_read') ───
  { title: 'From Poverty to Power', author: 'James Allen', category: 'mindset', status: 'to_read' },
  { title: 'The Archer', author: 'Paulo Coelho', category: 'mindset', status: 'to_read' },
  { title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', category: 'mindset', status: 'to_read' },
  { title: 'The Black Tulip', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Psychology of Laziness', author: 'Mohammad Shakeel', category: 'mindset', status: 'to_read' },
  { title: 'Master Your Mindset', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Courage to Be Disliked', author: 'Ichiro Kishimi', category: 'mindset', status: 'to_read' },
  { title: 'The Art of Being Alone', author: 'Gavrani', category: 'mindset', status: 'to_read' },
  { title: 'Power of Ignored Skills', author: 'Manoj', category: 'mindset', status: 'to_read' },
  { title: 'Trading for a Living', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Mental Game of Trading', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Disciplined Trader', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Trading Psychology 2.0', author: 'Brett', category: 'mindset', status: 'to_read' },
  { title: 'Just Keep Buying', author: 'Nick Maggiulli', category: 'mindset', status: 'to_read' },
  { title: 'The Power Law VC', author: 'Sebastián', category: 'mindset', status: 'to_read' },
  { title: 'The Art of Spending Money', author: 'Morgan Housel', category: 'mindset', status: 'to_read' },
  { title: 'The Anthology of Balaji', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Champions Mind', author: null, category: 'mindset', status: 'to_read' },
  { title: 'You Become What You Think', author: 'Shubham Kumar', category: 'mindset', status: 'to_read' },
  { title: 'Focus on What Matters', author: 'Darius Foroux', category: 'mindset', status: 'to_read' },
  { title: 'Your Brain is Playing Tricks on You', author: 'Albert Moukheiber', category: 'mindset', status: 'to_read' },
  { title: 'The Practicing Mind', author: 'Thomas Sterner', category: 'mindset', status: 'to_read' },
  { title: 'Master Your Thinking', author: 'Thibaut', category: 'mindset', status: 'to_read' },
  { title: 'Surrounded by Psychopaths', author: 'Thomas Erikson', category: 'mindset', status: 'to_read' },
  { title: 'Do Hard Things', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Shoe Dog', author: 'Phil Knight', category: 'mindset', status: 'to_read' },
  { title: 'Power Behind the Curtain', author: 'Dave Rumsfeld', category: 'mindset', status: 'to_read' },
  { title: 'Be So Good They Cannot Ignore You', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Leadership and Self Deception', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Deep Work', author: 'Cal Newport', category: 'mindset', status: 'to_read' },
  { title: 'The Pragmatic Programmer', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Phoenix Project', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Software Engineering at Google', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Things You Can See Only When You Slow Down', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Intelligent Investor', author: 'Benjamin Graham', category: 'mindset', status: 'to_read' },
  { title: 'A Brief History of Everyone Who Ever Lived', author: null, category: 'mindset', status: 'to_read' },
  { title: 'The Extended Mind', author: 'Annie Murphy', category: 'mindset', status: 'to_read' },
  { title: 'How Not to Be Wrong', author: 'Jordan Ellenberg', category: 'mindset', status: 'to_read' },
  { title: 'The Hard Thing About Hard Things', author: 'Ben Horowitz', category: 'mindset', status: 'to_read' },
  { title: 'Principles', author: 'Ray Dalio', category: 'mindset', status: 'to_read' },
  { title: 'Netflixes', author: 'Gina Keating', category: 'mindset', status: 'to_read' },
  { title: 'Winners Take All', author: 'Anand Giridharads', category: 'mindset', status: 'to_read' },
  { title: 'Daring Greatly', author: 'Brené Brown', category: 'mindset', status: 'to_read' },
  { title: 'High Growth Handbook', author: 'Elad Gil', category: 'mindset', status: 'to_read' },
  { title: 'The Undoing Projects', author: 'Michael Lewis', category: 'mindset', status: 'to_read' },
  { title: 'Factfulness', author: 'Hans Rosling', category: 'mindset', status: 'to_read' },
  { title: 'Good to Great', author: 'Jim Collins', category: 'mindset', status: 'to_read' },
  { title: 'One Hundred Years of Solitude', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Think Again', author: 'Adam Grant', category: 'mindset', status: 'to_read' },
  { title: 'The Anxious Generation', author: 'Jonathan Haidt', category: 'mindset', status: 'to_read' },
  { title: 'The Mountain is You', author: 'Brianna Wiest', category: 'mindset', status: 'to_read' },
  { title: 'Why We Sleep', author: 'Matthew Walker', category: 'mindset', status: 'to_read' },
  { title: 'The Power of Positive Thinking', author: 'Norman Vincent Peale', category: 'mindset', status: 'to_read' },
  { title: 'The Four', author: 'Scott Galloway', category: 'mindset', status: 'to_read' },
  { title: 'The Fountainhead', author: 'Ayn Rand', category: 'mindset', status: 'to_read' },
  { title: 'The Effective Executive', author: 'Peter Drucker', category: 'mindset', status: 'to_read' },
  { title: "The Innovator's Dilemma", author: 'Clayton Christensen', category: 'mindset', status: 'to_read' },
  { title: 'Business Adventures', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Einstein: His Life and Universe', author: null, category: 'mindset', status: 'to_read' },
  { title: 'Things Hidden Since the Foundation of the World', author: 'René Girard', category: 'mindset', status: 'to_read' },
  { title: "Surely You're Joking Mr. Feynman!", author: null, category: 'mindset', status: 'to_read' },
  { title: 'How to Get Filthy Rich in Asia', author: 'Mohsin Hamid', category: 'mindset', status: 'to_read' },
  { title: 'Think Like a Programmer', author: 'Anton Spraul', category: 'mindset', status: 'to_read' },
  { title: 'How to Build a Billion Dollar App', author: 'George Berkowski', category: 'mindset', status: 'to_read' },
  { title: 'Super Founders', author: 'Ali Tamaseb', category: 'mindset', status: 'to_read' },
  { title: 'Algorithms to Live By', author: 'Brian Christian', category: 'mindset', status: 'to_read' },
  { title: 'Enlightenment Now', author: 'Steven Pinker', category: 'mindset', status: 'to_read' },

  // ─── FICTION — READ (status: 'read') ───
  { title: 'Obsessed', author: 'Ted Dekker', category: 'fiction', status: 'read' },
  { title: 'Hit List', author: 'Chris Ryan', category: 'fiction', status: 'read' },
  { title: "Dead Man's Time", author: 'Peter James', category: 'fiction', status: 'read' },
  { title: "Where'd You Go?", author: 'Kehinde Ademoye', category: 'fiction', status: 'read' },
  { title: 'Beyond the Veil', author: 'Esther', category: 'fiction', status: 'read' },
  { title: 'Those in Peril', author: 'Wilbur Smith', category: 'fiction', status: 'read' },
  { title: 'Origin', author: 'Dan Brown', category: 'fiction', status: 'read' },
  { title: 'Deception Point', author: 'Dan Brown', category: 'fiction', status: 'read' },
  { title: 'Digital Fortress', author: 'Dan Brown', category: 'fiction', status: 'read' },
  { title: 'Angels and Demons', author: 'Dan Brown', category: 'fiction', status: 'read' },
  { title: 'The Rooster Bar', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'Sycamore Row', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'The Confession', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'The Broker', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'The Reckoning', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'Bleachers', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'The Appeal', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'Gray Mountain', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: 'The Associate', author: 'John Grisham', category: 'fiction', status: 'read' },
  { title: '1st Kill', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '2nd Chance', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '3rd Degree', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '4th of July', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '8th Confession', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '10th Anniversary', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '10th Hour', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: '18th Abduction', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Burn', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Humans Bow Down', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Cross Justice', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Merry Christmas', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Maximum Ride', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Run for Your Life', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'The Black Book', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Postcard Killers', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Hope to Die', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Cross the Line', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'NYPD Red 4', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Invisible', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Second Honeymoon', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'Private LA', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'The Family Lawyer', author: 'James Patterson', category: 'fiction', status: 'read' },
  { title: 'The Fix', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Zero Day', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'The Hit', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Stone Cold', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'First Family', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'The Fallen', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'King and Maxwell', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Simple Genius', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'The Collectors', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Redemption', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'The Innocent', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Last Man Standing', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'The Whole Truth', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Memory Man', author: 'David Baldacci', category: 'fiction', status: 'read' },
  { title: 'Master of the Game', author: 'Sydney Sheldon', category: 'fiction', status: 'read' },
  { title: 'Tell Me Your Dreams', author: 'Sydney Sheldon', category: 'fiction', status: 'read' },
  { title: 'If Tomorrow Comes', author: 'Sydney Sheldon', category: 'fiction', status: 'read' },
  { title: 'The Best Laid Plans', author: 'Sydney Sheldon', category: 'fiction', status: 'read' },

  // ─── FICTION — TO READ (status: 'to_read') ───
  { title: '19th Christmas', author: 'James Patterson', category: 'fiction', status: 'to_read' },
];

async function seed() {
  const existing = await db.select().from(books).limit(1);
  if (existing.length > 0) {
    console.log('Books table already seeded, skipping.');
    return;
  }
  console.log('Seeding books table...');
  await db.insert(books).values(bookData);
  console.log(`Seeded ${bookData.length} books.`);
}

seed().catch(console.error);
